### ISSUE TITLE
Center 2 team members

### ISSUE THREAD

**Issue by craigeley** [y7kim/agency-jekyll-theme#15]
Hi there—love this theme, and pretty new to Jekyll, but can you give me any tips on how to center the two images when I only have two people in a team?

**Comment by craigeley** [comment]
Changing the class to col-sm-6 works, but then the two columns appear kind of far apart. I'll keep tinkering in these column classes, perhaps.

**Comment by y7kim** [comment]
Hey Craig,

If you want 2 columns and smaller space in between, try 'col-sm-4
col-sm-offset-2' for the first element and 'col-sm-4' for the second.

Rick

**Comment by craigeley** [comment]
Thanks, Rick. But since this is called within a "for" loop how would I adjust the two elements independently?

**Comment by y7kim** [comment]
Yes, of course - you can just take it out of the loop.  Replace the div
block on line 10 with something like this:

https://gist.github.com/y7kim/b383b36b843ac6e454b1

**Comment by craigeley** [comment]
Cool. Thanks, Rick!
