### ISSUE TITLE
Agency - Portfolio Grid Modal Order

### ISSUE THREAD

**Issue by dawnmercurio** [y7kim/agency-jekyll-theme#17]
Hello, Thanks for sharing this elegant template.

Can you explain why the portfolio grid shows modals in the order of 1-3, then the second row 6, 4, 5?

I looked at the post names/dates and they all seem in order so I can't figure out why they present this way. 

Thanks for your time.
Dawn

**Comment by y7kim** [comment]
Hi Dawn,

Were you able to resolve your issue?  Sorry, this email squeaked past my
attention and I apologize.  Let me know if you need any assistance.

Best,

Rick

**Comment by dawnmercurio** [comment]
Hi Rick
It isn't much of an issue. More of a question if you can help me understand
why the portfolio grid posts do not present in chronological (date) order.
I am able to work around it, but it seemed as though your intention would
have been to have the sequence go 1-6, but the second row is out of order.

thanks for your time,
Dawn

**Comment by y7kim** [comment]
Hi Dawn,

Yes I see now, and yes you are correct.  Here is the problem:

The date in the filename is actually incorrect for project 6 - if you look
at the file contents for '_2014-07-13-project-6.markdown_' , you will see
that the value in the date field is actually '2014-07-15' and not
2014-07-13.  This date field takes precedence over the date in the filename
if it is present.  It is useful also if you want to specify hours, minutes,
seconds, and timezone for the posts for finer control over the order in
which they are displayed.

So, it is behaving as intended, but the filename is the source of
confusion.  I will update the repo as necessary.

Thanks for using the theme and noticing this particular issue.  Let me know
if you have any other questions.

Rick
