### ISSUE TITLE
differences between jekyll theme and bootstrap theme

### ISSUE THREAD

**Issue by zbeekman** [y7kim/agency-jekyll-theme#19]
I noticed one of the main differences between the bootstrap theme and the jekyll theme has to do with some of the 3rd party libraries/elements the agency theme uses. In particular I am referring to font-awesome and bootstrap. AFAICT font-awesome has been left completely in tact. However, it appears that this is not the case for bootstrap. In particular, `bootstrap.css` (or the minified version) appears to have been yoinked from [bootswatch](http://bootswatch.com). I have two questions about this:

1) What was the motivation for using the bootswatch version? Was it simply to cut down on the amount of bootstrap assets needed, and slim down the site?

2) Would getting rid of the bootswatch version and replacing it with vanilla bootstrap be liable to cause any issues? I am thinking that it might be worthwhile to use grunt or gulp to automate building of the site (rather than having github do it for me) so that I can minify things (for speed) and also have better management of 3rd party packages via bower or npm.

**Comment by y7kim** [comment]
zbeekman,

1) I can't really answer to the motivation - you can ask https://github.com/jeromelachaud however, as this theme is actually based off his work with the Freelancer theme - but I can't see performance being the reason.

2) I can't think of any reason why you couldn't drop in vanilla Bootstrap in its place - I just tried it quickly and while I see some minute differences in margin and spacing in the navbar, it renders nearly identically.

**Comment by zbeekman** [comment]
It seems like the main difference is the inclusion of some liquid variables for selecting site color themes and the removal of the glyph icons and other extraneous stuff.
