### ISSUE TITLE
Template files loaded to FTP are displayed incorrectly

### ISSUE THREAD

**Issue by olexth** [y7kim/agency-jekyll-theme#29]
Hi, Rick!
First of all, thank you for such good looking template, great work!
I am not sure if it is actually issue of my lack of Jekyll knowledge, or actual problem.
When I am downloading Agency Theme and starting Jekyll - everything looks fine locally.
But when I am dragging files from _site folder to FTP, or making the same using glynn, I have that in browser:
![screenshot 2016-01-19 18 48 51](https://cloud.githubusercontent.com/assets/2251522/12425853/6561a838-bedf-11e5-9359-756c19198ac4.png)
Like some file is missing or broken. Any ideas on this?
Sorry for definitely noob question, web is not my main area.

Best regards,
Alex

**Comment by y7kim** [comment]
Hey Alex,

Thanks for the kind words.  Please see lines 1 and 2 in _config.yml.

The values for url and baseurl should those for your server, so it knows exactly where to look for those files.

Let me know if that works.

Rick

**Comment by olexth** [comment]
Oh, really simple.
Now it's working!

Thank you and have a good day!

Best regards,
Alex

**Comment by y7kim** [comment]
Glad I could help!
