### ISSUE TITLE
Colors configuration doesnt work...

### ISSUE THREAD

**Issue by rodrigograca31** [y7kim/agency-jekyll-theme#42]
Because of this commit: https://github.com/y7kim/agency-jekyll-theme/commit/730995b9e4cda4eb11564bc0ad604b1e35b42083

The "variables path" was changed from `site.color.primary` to `site.data.template.color.primary` and that was not reflected on `_includes/css/bootstrap.min.css` ...

I've noticed that because the form submission success message did not had a background color....

I will send a simple PR that replaces `site.color.primary` by `site.data.template.color.primary`...

**Comment by rodrigograca31** [comment]
BTW, Thanks for the theme!
(It's my first time using jekyll...)

**Comment by y7kim** [comment]
You're most welcome.  Thanks for contributing!
