### ISSUE TITLE
Navbar doesn't appear fast enough

### ISSUE THREAD

**Issue by jellysquider** [y7kim/agency-jekyll-theme#51]
I noticed an issue with navbar on the demo example (and later on my own website). 
The transition to "Services" when scrolled down by mouse or by keyboard arrows is not smooth enough.

I believe the issue is that it doesn't disappear fast enough.
Check out my screenshot: NavBar covers the Header.

![navbar snail](https://cloud.githubusercontent.com/assets/16536278/20238739/d1937d0e-a8a6-11e6-9174-6e896cafe61f.png)

Compare it with [original Bootstrap theme](https://blackrockdigital.github.io/startbootstrap-agency/):

![original navbar](https://cloud.githubusercontent.com/assets/16536278/20239003/2289fada-a8ac-11e6-96ba-f1b1b3b8cca9.png)

**Comment by kimbergee** [comment]
@jellysquider Did you figure out your issue? You can change when the navbar appears by going into the cbpAnimatedHeader.js file. It's in the js folder. I found that changing it from 300 too 100 works well.

**Comment by TT--** [comment]
I also found that value of 100 is consistent with the [source theme](https://github.com/BlackrockDigital/startbootstrap-agency/blob/master/js/agency.js#L29) and have used that in the above PR.
