### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by opensorceror** [y7kim/agency-jekyll-theme#55]
I tried cloning this and running `jekyll serve`, but it looks like the Gemfile is missing?

**Comment by bennettchidoro** [comment]
@opensorceror in ` _config.yml` just comment out the first two lines. "url: https://y7kim.github.io
and baseurl: /agency-jekyll-theme/." This worked for me.

**Comment by opensorceror** [comment]
Yep, that worked. Thanks!
